# Generated by Django 5.1.3 on 2024-11-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_library/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attributed_to', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French')], default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media_library/videos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='mission',
            new_name='about_text_english',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='categories',
            new_name='campaign_name_english',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='scope',
            new_name='scope_of_mission',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='website_url',
            new_name='website_url_english',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='additional_media',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='charity',
            name='about_text_french',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='campaign_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='campaign_goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='campaign_language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='charity',
            name='campaign_name_french',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='campaign_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_logo_english',
            field=models.ImageField(blank=True, null=True, upload_to='charity_logos/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='communication_language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Bilingual', 'Bilingual')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_email_english',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_email_french',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_name_french',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='emotive_image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_settings/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='main_charity_image_english',
            field=models.ImageField(blank=True, null=True, upload_to='page_visuals/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='main_charity_image_french',
            field=models.ImageField(blank=True, null=True, upload_to='page_visuals/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='monthly_donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='monthly_donation_impact_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='monthly_donation_impact_french',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='one_time_donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='one_time_donation_impact_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='one_time_donation_impact_french',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='popular_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='popular_name_french',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='primary_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='primary_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='search_image_english',
            field=models.ImageField(blank=True, null=True, upload_to='donation_settings/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='search_image_french',
            field=models.ImageField(blank=True, null=True, upload_to='donation_settings/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='short_intro_text_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='short_intro_text_french',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='website_url_french',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, to='frontend.category'),
        ),
        migrations.AddField(
            model_name='charity',
            name='images',
            field=models.ManyToManyField(blank=True, to='frontend.image'),
        ),
        migrations.AddField(
            model_name='charity',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='frontend.quote'),
        ),
        migrations.AddField(
            model_name='charity',
            name='videos',
            field=models.ManyToManyField(blank=True, to='frontend.video'),
        ),
    ]
